db:
  image: mysql:8
  container_name: db
  volumes:
    - db-data:/var/lib/mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: react_insta
    MYSQL_USER: assqr
    MYSQL_PASSWORD: 123456
  ports:
    - 3306:3306
  command: --default-authentication-plugin=mysql_native_password # <- 追加
